import unittest
from job_hunter.core.email_extractor import extract_emails


class TestEmailExtractor(unittest.TestCase):

    def test_basic_extraction(self):
        text = "Send your resume to hr@company.io for the AI role"
        result = extract_emails(text)
        self.assertEqual(result, ["hr@company.io"])

    def test_multiple_emails(self):
        text = "Contact john@acme.com or sarah@acme.com for details"
        result = extract_emails(text)
        self.assertEqual(result, ["john@acme.com", "sarah@acme.com"])

    def test_deduplication(self):
        text = "Email me at test@firm.org. Again: test@firm.org"
        result = extract_emails(text)
        self.assertEqual(result, ["test@firm.org"])

    def test_blacklisted_domains_filtered(self):
        text = "Contact us at user@example.com or fake@test.com"
        result = extract_emails(text)
        self.assertEqual(result, [])

    def test_noreply_filtered(self):
        text = "From noreply@linkedin.com and no-reply@jobs.com"
        result = extract_emails(text)
        self.assertEqual(result, [])

    def test_empty_input(self):
        self.assertEqual(extract_emails(""), [])
        self.assertEqual(extract_emails(None), [])

    def test_no_emails(self):
        text = "This job posting has no contact info whatsoever."
        result = extract_emails(text)
        self.assertEqual(result, [])

    def test_case_insensitive(self):
        text = "Email HR@BigCorp.COM for this role"
        result = extract_emails(text)
        self.assertEqual(result, ["hr@bigcorp.com"])

    def test_email_in_linkedin_post_style(self):
        text = """We're hiring a Senior ML Engineer!
        If interested, drop your resume at careers@techstartup.ae
        #hiring #AI #machinelearning"""
        result = extract_emails(text)
        self.assertEqual(result, ["careers@techstartup.ae"])

    def test_mixed_valid_and_invalid(self):
        text = """Contact: real.person@company.co
        Auto-generated by noreply@system.com
        Visit example@example.com for more"""
        result = extract_emails(text)
        self.assertEqual(result, ["real.person@company.co"])


if __name__ == "__main__":
    unittest.main()
